name: Build and Package Boops Client

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.18'

    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install -y rpm build-essential dpkg-dev

    - name: Build Go binary
      run: |
        go build -o boops main.go

    - name: Create Debian package
      run: |
        mkdir -p debian/usr/local/bin debian/usr/share/doc/boops
        cp boops debian/usr/local/bin/
        cp boops.service debian/usr/share/doc/boops/
        dpkg-deb --build debian/ boops_0.1_amd64.deb

    - name: Create RPM source tarball
      run: |
        tar -czf boops-0.1.tar.gz main.go go.mod go.sum client system boops.spec boops.service

    - name: Build RPM package
      run: |
        rpmbuild --define "_topdir $HOME/rpmbuild" -tb boops-0.1.tar.gz

    - name: Upload Debian package artifact
      uses: actions/upload-artifact@v2
      with:
        name: boops_0.1_amd64.deb
        path: boops_0.1_amd64.deb

    - name: Upload RPM package artifact
      uses: actions/upload-artifact@v2
      with:
        name: boops-0.1.x86_64.rpm
        path: ~/rpmbuild/RPMS/x86_64/boops-0.1.x86_64.rpm
