CREATE DATABASE IF NOT EXISTS boopsdb;
USE boopsdb;

CREATE TABLE machines (
  id INT AUTO_INCREMENT PRIMARY KEY,
  hostname VARCHAR(255) NOT NULL,
  model_info TEXT,
  usage_desc TEXT,
  memo TEXT,
  last_alive DATETIME,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE interfaces (
  id INT AUTO_INCREMENT PRIMARY KEY,
  machine_id INT NOT NULL,
  name VARCHAR(50) NOT NULL,
  ip_address VARCHAR(45) NOT NULL,
  subnet_mask VARCHAR(45) NOT NULL,
  gateway VARCHAR(45),
  FOREIGN KEY (machine_id) REFERENCES machines(id) ON DELETE CASCADE
);
