name: Build and Upload Boops Client

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    strategy:
      matrix:
        arch: [ amd64, arm64 ]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.18'

    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install -y rpm build-essential dpkg-dev qemu-user-static

    - name: Build Go binary for ${{ matrix.arch }}
      env:
        GOARCH: ${{ matrix.arch }}
      run: |
        go build -o boops-${{ matrix.arch }} main.go
      working-directory: ./boops-client

    - name: Upload built binary to server
      run: |
        curl -F "file=@boops-${{ matrix.arch }}" https://file.booyah.dev/BoopsDB-Client/boops_0.1_${{ matrix.arch }}.binary
      working-directory: ./boops-client
