#!/bin/bash
set -e

# Create necessary directories and set permissions
mkdir -p /etc/boops
touch /etc/boops/config.json
chmod 644 /etc/boops/config.json

# Copy systemd service and timer files to /etc/systemd/system/
cp /usr/share/doc/boops/boops.service /etc/systemd/system/
cp /usr/share/doc/boops/boops.timer /etc/systemd/system/

# Reload systemd and enable the boops service and timer
systemctl daemon-reload
systemctl enable boops.timer
systemctl start boops.timer
