#!/bin/bash
set -e

# Create necessary directories and set permissions
mkdir -p /etc/boops
touch /etc/boops/config.json
chmod 644 /etc/boops/config.json

# Copy systemd service file to /etc/systemd/system/
cp /usr/share/doc/boops/boops.service /etc/systemd/system/

# Reload systemd and enable the boops service
systemctl daemon-reload
systemctl enable boops.service
systemctl start boops.service
